name: nomad-pack Workflow

on:
  - push

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `nomad-pack`
        uses: ksatirli/setup-nomad-pack@0.1.3
        id: setup
        with:
          version: "0.0.1-techpreview2"

      - name: Print version output
        run: echo "${{ steps.setup.outputs.version }}"

      - name: Run `nomad-pack version`
        run: nomad-pack version
