name: nomad-pack

on:
  push:


jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `nomad-pack`
        uses: ksatirli/test-action@0.2.0
        id: setup
        with:
          version: "0.0.1-techpreview2"

      - name: Print `$PATH`
        run: which nomad-pack

      - name: Run `nomad-pack`
        run: nomad-pack
        # `nomad-pack` exits with 127, so we force-continue on error
        continue-on-error: true

      - name: Run `nomad-pack info` for `simple_service`
        run: "nomad-pack info ./packs/simple_service"

      - name: Run `nomad-pack run` for `simple_service`
        run: "nomad-pack run ./packs/simple_service"
        env:
          NOMAD_ADDR: "${{ secrets.NOMAD_ADDR }}"
        continue-on-error: true
