name: packer

on:
  push:


jobs:
  setup-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run `packer` above
        run: packer version

      - name: Setup `packer` from renamed action
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        
        id: setup
        with:
          version: "1.8.1"

      - name: Print `$PATH`
        run: which packer

      - name: Run `packer` below
        run: packer version
        
      - name: Run `packer`
        run: packer init "${{ github.action_path }}/../packer_templates/hello-world.pkr.hcl"

      - name: Setup `packer` from renamed action
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        
        id: ranch
        with:
          version: "ranch"
