name: packer

on:
  push:


jobs:
  setup-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup `packer` from renamed action
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        
        id: setup
        with:
          version: "1.8.1"

      - name: Print `$PATH`
        run: which packer

      - name: Run `packer` version
        run: packer version
        
      
      - name: Run `packer` init
        run: packer init "${{ github.action_path }}./packer_templates/hello-world.pkr.hcl"

      - name: Try to setup packer for an invalid verison
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        
      - name: Run `packer` version
        run: packer version
        
        
        id: ranch
        with:
          version: "ranch"
      - name: Try to setup packer for a verison that has yet to be released
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        id: packer3
        with:
          version: "3.0.0"
          
      - name: Run `packer` version
        run: packer version
        
