name: packer

on:
  push:


jobs:
  setup-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup `packer` from renamed action
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        id: setup
        with:
          version: "1.8.1"

      - name: Print `$PATH`
        run: which packer

      - name: Print packer version
        run: packer version
        
      - name: Validate Packer version is 1.8.1
       ## Grab the first line of the packer version only to remove out of date version notice
        if: ${{ packer version | head -1 }} != "Packer v1.8.1"
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Expected packer 1.8.1 to be installed')
      
      - name: Run `packer` init
        run: packer init "${{ github.action_path }}./packer_templates/hello-world.pkr.hcl"

      - name: Try to setup packer for an invalid verison
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        id: ranch
        with:
          version: "ranch"
        continue-on-error: true
          
      - name: Validate invalid version failed
        if: steps.ranch.outcome == "success"
        run: exit 1
        
      - name: Try to setup packer for a verison that has yet to be released
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        id: packer3
        with:
          version: "3.0.0"
        continue-on-error: true
        
      - name: Validate invalid version failed
        if: steps.packer3.outcome == "success"
        run: exit 1
        
      - name: No version defaults to latest
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        id: latest
      
      - name: Validate Packer version is latest (currently hardcoded, need to refactor)
        if: ${{ packer version }} != "Packer v1.8.4"
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Expected packer 1.8.4 to be installed')
      

